# Assesment

## Ques1)   Mention some of the advantages of python?


#### ans )  Advantages of python are--
            1. Easy to learn and read.
            2. Extensive standard library.
            3. Versatile for various applications.
            4. Strong community support.
            5. Highly readable code.
            6. Open source and free to use.

### Ques2) What are local variables and global variables in Python?

#### ans) Local varibles- 
                         Local variables are defined within functions or blocks and are accessible only within their scope. They are temporary and get destroyed after the function or block execution.

##### example-
               def example_function():
    x = 10  
    print(x)

example_function()  # Output: 10
print(x)   This will raise a NameError since 'x' is a local variable within the function.


####     global variables-
                          Global variables are defined at the top level of the script and can be accessed and modified from anywhere in the code. They retain their values throughout the program's execution.

#### example-
             e.g.


```
a=5

def func:
  b=7
  return
```

Here a is a global variable and can be accessed anywhere, including in the function func, whereas b is a local variable and is local to the function func, i.e. it can be accessed only within func.


### Ques3) What is Lambda Functions in Python?

##### ans) lambda function-
                           lambda functions in Python are small, anonymous functions that can take any number of arguments but can only have one expression. They are defined using the lambda keyword and are often used for short, simple operations or as arguments in higher-order functions. it will take only one line of argument.

##### example- 
c=lambda a,b : a+b
c(6,3)
```
The output will be 9 as this lambda function adds the given two arguments.



### Ques4) What is a Negative Index in Python?

##### ans) negative index-
          Negative index is index from the last element of the object we are indexing instead of the first. So, for                        e.g. if we have a list a = [10,22,13,44,65], then a[-1] will give us 65 and a[-2] will give us 44.

### Ques5)  What is the difference between tuples and lists?

##### ans)  Tuple-
             Tuples are similar to lists but are unchangable, i.e. we cannot add/remove elements and cannot change the values of elements inside the tuples.also, Tuples are denoted by ().

#####     Lists-
                On the other hand, lists can append new elements, remove existing ones and change values of existing elements too.Lists are denoted by []


### Ques6) What is a dynamically typed language?

##### ans) dynamically typed language-
             a dynamically typed language is one where the type of a variable is determined at runtime based on the value it holds. Developers don't need to explicitly declare the data type of variables, providing flexibility but potentially leading to runtime type errors. Examples include Python, JavaScript, Ruby, and PHP.

### Ques7) What are the data types available in python?Brief about it?

##### ans) data types-
int: integers, i.e. ...,-4,-3,-2,-1,0,1,2,3,4,...

str: strings (sequence of characters), enclosed by single or double quotes

bool: True or False logical variables

list: collection of elements of various data types, and can be changed, denoted by []

tuple: collection of elements of various data types, that cannot be changed, denoted by ()

dict: short for dictionary, collection of key-value pairs, denoted by {} with key-value pairs represented as key:value

set: unordered, unchangeable collection of unique elements, denoted by {}, new elements can be added/removed

### Ques8) Why we have to use functions in Python? Explain with an example?

##### ans) Fucntions-
          We need to use functions for tasks that we have to perform again and again, so that we do not need to retype the same code every time but can call the corresponding function instead.

e.g. the following function combines the two lists given to it and returns the resulting list.

#### 
     def combine_lists (a,b):
  c=list()
  for i in a:
    c.append(i)
  for i in b:
    c.append(i)
  return c

a=[1,2,3]
b=['a','b','c']
c=combine_lists(a,b)
c

[1, 2, 3, 'a', 'b', 'c']

### Ques9) What is the difference between function and generators? Give an example?

#### ans)
Generators are like functions but instead of return they use yield, which appends elements to the generator object which is then returned. We can use for loop to iterate through the returned generator object.

They are advantageous over functions when the input is very large, as functions will take a lot of time and memory but generators will display the output in the console only, consuming much lesser time and memory. Functions will compute the entire thing before returning, but generators will go one element at a time.

e.g.


```
def gen(n):
  for i in range(n):
    yield i
```

This generator will generate a sequence of the first n whole numbers



In [4]:
def gen(n):
  for i in range(n):
    yield i

a = gen(7)
for i in a:
  print (i)

0
1
2
3
4
5
6


### Ques10) Explain brief about conditional statements with an example?


##### conditional statements-
  Conditional statements are used in programming to make decisions based on certain conditions. They allow you to execute specific blocks of code if a condition is true and an alternative block if it's false. The most common forms are "if" statements (for single conditions) and "if-else" statements (for two possibilities). They provide the ability to create dynamic and flexible programs.

In [5]:
a = 7
if (a<6):
  print('This prints if the statement is true')
else:
  print('This prints if the statement is false')

This prints if the statement is false


### Ques11) Why we have to use exceptional handling in python? What are the keyword used to handle the error , give one example?


##### ans) 
We use exception handling to handle cases where an abnormal event occurs, i.e. an exception occurs, that can crash the program. This could be an input that should not be entered, like making the divisor in a division 0, or a size for a list so large that it isn't possible to make that list due to memory limitations. To avoid crashing the program, we use exception handling to handle these exceptions and ask the user to retry, or do not compute that line, etc.

The keywords used are try to check for exceptions and except to handle the exception, and raise can also be used to raise a specific error.

e.g. the following code is for division in which the code handles the case where the division doesn't happen successfully, like in the case the user enters 0 as the divisor, and asks them to retry.

In [7]:
while True:
  try:
    a=int(input('Dividend: '))
    b=int(input('Divisor: '))
    print(a,'/4',b,'=',a/b)
    break
  except:
    print('Error' )

Dividend: 4
Divisor: 2
4 /4 2 = 2.0


### Ques12)  Define class and objects with an example?

#### ans)
  A class is a blueprint that defines the structure and behavior of objects in object-oriented programming. Objects are instances of a class, each having its own unique data and methods to perform actions. For example, a class called Car could have attributes like make, model, and year, and methods like start(), stop(), and get_status() to control and interact with individual car objects.

In [8]:
class student:
  def __init__(self,name,surename):
    self.name=name
    self.surename=surename

s = student('Divya','Rajawat')
print(s.name,s.surename)

Divya Rajawat


In [11]:
print('Q13. Write a program to swap the two numbers in python?')

a=10
b=20
print('Before: a = ',a,", b = ",b)
(a,b)=(b,a)
print('After: a = ',a,'b = ',b)

Q13. Write a program to swap the two numbers in python?
Before: a =  10 , b =  20
After: a =  20 b =  10


In [10]:
print('Q14. Write a palindrome program in python')

def palindrome (a):
  l=len(a)
  for i in range(l):
    if a[i]!=a[l-i-1]:
      return False
  return True

print(palindrome('abcabca'))
print(palindrome('abcba'))

Q14. Write a palindrome program in python
False
True


### Ques15)  What is the use of numpy array over list?

#### ans) advantages of numpy array over list are-
        1. numpy takes less memory raher than list.
        2. it is very convienient to use.
        3. it takes less time.

### Ques16) Explain in brief about reshape in numpy with an example?


##### ans)
Reshape changes the dimensions of the numpy array into the given dimensions. For example, the following code changes the given array from a 4x4 array to a 8x2 array.

In [13]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

print(a,'\n')

a=np.reshape(a,(8,2))
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


### Ques17) What is the use of pandas explain in brief?


##### ans) Pandas-
                andas is a powerful python library that can be imported and then used to analyse, manipulate and clean data.

We can use pandas to import data in the form of data frames and then clean it to prepare it for further processing, e.g. machine learning. We can analyse the data by filtering it, printing summaries and stats of the data, and make modifications to it in order to clean it.

### Ques18) What do you mean by supervised machine learning and unsupervised machine learning? Explain in brief?

##### ans) Supervised Machine Learning- 
                                      Supervised machine learning is the type of machine learning that uses labeled data, i.e. both independent and dependent variables, to create a model that can then predict the label of newly input data.

Examples include regression (linear, multilinear, logistic etc.), decision tree, random forest, KNN etc.


#####    Unsupervised Machine Learning-
                                    Unsupervised learning on the other hand uses data that is unlabeled, i.e. contains only independent variables and not dependent variables to create a model that figures out clusters or similar data points on its own.

Examples include k-means clustering, etc.

### Ques19) Differenciate between Decision tree and Random forest?


##### ans)
A decision tree is the basic unit of a random forest.

A decision tree is a structure in the form of one root nodes, several decision nodes and leaf nodes that contain the final output. We start from the root node, follow the branch that satisifies our condition and continue till we reach a leaf node, that contains the output.

A random forest on the other hand is a collection of several decision trees.

### Ques20) What do you mean by forward propagation and backward propagation in ANN?

##### ans)
Forward propagation in an ANN is when we move forward, i.e. left to right, i.e. towards the direction of the output layer.

Backward propagation is when we move in the opposite direction, towards the input layer, i.e. the output of a hidden layer or the output layer itself is used as the input in a previous layer. This is done to update weights and reduce loss.

### Ques21) Explain the working flow of ANN and CNN?

##### ans)
ANN consists of input layer, hidden layers, activation functions, bias, weights and output layer.

We start from the input layer, that adds all the inputs multiplied by their weights, adds the bias and uses the activation function to produce an output which goes on to the next layer, and so on, until we reach the final output layer. During this process we also update weights to reduce loss.

CNN consists of an input image, that goes through optional padding. Then several rounds (as required) of convolution, and pooling happen along with filters, to produce a fully connected layer. Then the output produced is flattened. This flattened image is used as input to the fully connected layer to produce a final output which could be a classification of the original image.

### Ques22)  What is the use of activation function and optimizers?

##### ans)
Activation functions are used to transform inputs to outputs. They introduce non linearity to the network.

Optimizers are used to minimize loss.

### Ques23)  What is the difference between R square and adjusted Rsquare?

##### ans)
R square is simply the sum of squares of difference between actual and predicted values.

Adjusted R square on the other hand is the R square value adjusted for the number of independent variables used to calculate the predictions. It is equal to 1 - [(1-Rsquare)(n-1)]/(n-k-1)], where n=no. of data points, and k=no. of independent variables. It helps us know if adding independent variables is benefitting our model or not.

### Ques24) What do you mean by LSTM in RNN?


##### ans) 
LSTM is short for long short term memory in RNN (recurrent neural networks).
It is an improved version of RNN that uses feedback to remember long term dependencies unlike usual RNN that remembers only short term dependencies.

### Ques25) What is the use of image processing?

##### ans)
Image processing is used to analyse images, build models for image classifications, manipulate images and modify their pixels, etc. It can be used in image classification, or editing of images to for example remove the background, etc.

### Ques26) What are the steps involved in NLP?

### ans)  The steps involved in natural language processing are:

1. Lexical analysis
2. Syntactical analysis
3. Semantic analysis
4. Discourse integration
5. Pragmatic analysis

### Ques27) What do you mean by bias and variance?


##### ans)
Bias is the model error that happens due to under fitting, or not viewing the data enough times to draw correct patterns from it.

Variance on the other hand happens with over fitting, when the data is viewed too many times and results in the model being very accurate with the training data but failing with new data.

### Ques28) What are the steps involved in machine learning to create model?

##### ans) To create a model, we:

1. Import the dataset using which we have to create the model
2. Perform EDA (exploratory data analysis), in which we understand the dataset
3. Clean the dataset to handle NULL values, check the data types of columns, etc.
4. Pre-processing in which we perform label encoding, binary encoding, scaling etc. and split our dataset into training and testing data
5. Model creation using linear regression, logistic regression, KNN, etc. as required
6. Evaluation and validation of model using metric analysis which includes metrics like accuracy, confusion matrix, etc.